### ISSUE TITLE
Programming Rumpus Board with ISP

### ISSUE THREAD

**Issue by malwikl** [fd0/rumpus#2]
Hi,

I found an old Rumpus board in my "Krabbelkiste" (you have to imagine a big box full of stuff) and wanted to use it again.

Therefore I wanted to flash some Software to the processor using another Arduino Nano as ISP with ArduinoISP, but somehow I cant get this to work... I followed the wiring described here:
http://www.martyncurrey.com/arduino-nano-as-an-isp-programmer/

I choose an ATMEGA168 und set the jumpers RIN, VCC,GND,SCK,MISO,MOSI but this did not help. Any suggestions or a hint what I might be doing wrong?

Thanks
Malwikl

**Comment by fd0** [comment]
That sounds exactly right, I don't know why it isn't working. Did you use a blank ATMEGA? If the controller is configured with the wrong crystal settings it may not answer via ISP, that's the only guess I have right now.

The original ATMEGA168 that came with the board had an USB bootloader installed, so there's no need to use ISP at all.

**Comment by malwikl** [comment]
Do you have a hint how to use the USB boot loader?

**Comment by fd0** [comment]
Yes: Plug the board into USB (no external power), then press the reset button, afterwards the blink frequency of the LED changes and there'll be a new USB device.

**Comment by malwikl** [comment]
Yes, it blinks for about 10 seconds but I only get this:
[866760.228959] usb 1-1.5: new low-speed USB device number 98 using dwc_otg
[866760.648977] usb 1-1.5: device not accepting address 98, error -71
[866760.649264] usb 1-1-port5: unable to enumerate USB device

Hmm too bad... The original description on how to flash the original bootloader seems to be missing on lochraster.org. Do you have the descriptions and explanations anywhere left?

**Comment by fd0** [comment]
Are all the right jumpers for USB communication are set? The most important ones are:
- USBPUD (USB Pull-Up resistor)
- D+ and D- (USB data lines)

It looks like the bootloader is still active, but the USB communication does not work.

Can you tell me which URL you're missing?
